// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDykliJR29nNrQh7_ABCmGzi2X1RNCAMgQ',
    appId: '1:984549549070:web:f4d6465858239b808b885f',
    messagingSenderId: '984549549070',
    projectId: 'thread-clone-tutorial-a7c70',
    authDomain: 'thread-clone-tutorial-a7c70.firebaseapp.com',
    storageBucket: 'thread-clone-tutorial-a7c70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJoSIxeFVHX0pon1OMINbKu-olEq5nm98',
    appId: '1:984549549070:android:a6d17fee11dda4f78b885f',
    messagingSenderId: '984549549070',
    projectId: 'thread-clone-tutorial-a7c70',
    storageBucket: 'thread-clone-tutorial-a7c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjDt3xUsZpMC6RBnlMyQjfbDVZSwTzm1E',
    appId: '1:984549549070:ios:e3287d5c1aba9d248b885f',
    messagingSenderId: '984549549070',
    projectId: 'thread-clone-tutorial-a7c70',
    storageBucket: 'thread-clone-tutorial-a7c70.appspot.com',
    iosBundleId: 'com.example.threadCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjDt3xUsZpMC6RBnlMyQjfbDVZSwTzm1E',
    appId: '1:984549549070:ios:30c47fc17d3f40fa8b885f',
    messagingSenderId: '984549549070',
    projectId: 'thread-clone-tutorial-a7c70',
    storageBucket: 'thread-clone-tutorial-a7c70.appspot.com',
    iosBundleId: 'com.example.threadCloneFlutter.RunnerTests',
  );
}
